baseURL = 'https://old-kampala.sirapollokaggwaschools.co.ug/'
locale = 'en-us'
title = 'Sir Apollo Kaggwa Primary School - Old-kampala'
theme = "saks-theme"

[params]
logo = "/img/logo.png"
mainSchool = false
